name = "fluoresce"
version = "1.0.1"

description = "A fun type-tetris Gleam library for algebraic effects, the Continuation monad, and classical logic types."
licences = ["MPL-2.0"]

repository = { type = "github", user = "RyanBrewer317", repo = "fluoresce" }
links = [{ title = "Author Website", href = "https://ryanbrewer.dev" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
